import { runSshCommand, getHostConnectionInfo } from "../ssh";
import { ensurePrivateKeyDeployed, ensurePublicKeyAuthorized } from "../backup/keys";
import { ensureRemoteDir, ensureRsyncReachable } from "../backup/transfer";
import { listReplications, updateReplicationStatus, type Replication } from "./replication";

const SETUP_TIMEOUT_MS = 60_000;
const STATUS_TIMEOUT_MS = 15_000;
const LSYNCD_CONFIG_PATH = "/etc/lsyncd/lsyncd.conf.lua";

/**
 * lsyncd runs exactly one config file per service instance (the packaged systemd unit on
 * Debian/Ubuntu always points at LSYNCD_CONFIG_PATH) — so every enabled 'folder' replication whose
 * source is this host has to live together in one regenerated file, not one file per replication.
 * Regenerated in full and the service restarted on every add/remove/toggle rather than trying to
 * patch the file in place, which would need a real Lua-aware editor to do safely.
 */
function buildLsyncdConfig(
  entries: {
    sourcePath: string;
    targetPath: string;
    targetUser: string;
    targetAddress: string;
    targetPort: number;
    keyPath: string;
    targetOwner: string | null;
    targetMode: string | null;
  }[]
): string {
  const syncBlocks = entries
    .map((e) => {
      // Every item here becomes one entry in a Lua table of separate argv strings, so each has to
      // be its own properly-quoted Lua string literal (luaString handles that uniformly) — a bare
      // "-e" with no quotes would be invalid Lua syntax, not just a wrong argument.
      const extra = [
        luaString("-e"),
        luaString(
          `ssh -i ${e.keyPath} -p ${e.targetPort} -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10`
        ),
      ];
      // --chown/--chmod override whatever ownership/permissions rsync -a would otherwise carry
      // over numerically from the source (meaningless here — the receiving side runs this as its
      // own unprivileged, backup-dedicated SSH account, not root, and not necessarily sharing any
      // uid/gid with the source at all) — this is what actually gets files onto B owned by (and
      // permissioned for) whatever account runs the web server there.
      if (e.targetOwner) extra.push(luaString(`--chown=${e.targetOwner}`));
      if (e.targetMode) extra.push(luaString(`--chmod=${e.targetMode}`));

      return `sync {
  default.rsyncssh,
  source = ${luaString(e.sourcePath)},
  host = ${luaString(`${e.targetUser}@${e.targetAddress}`)},
  targetdir = ${luaString(e.targetPath)},
  delay = 1,
  rsync = {
    archive = true,
    compress = true,
    _extra = {
      ${extra.join(",\n      ")}
    }
  }
}`;
    })
    .join("\n\n");

  return `-- Generated by Homelab Panel (high availability — folder replication). Do not edit by hand:
-- this file is fully regenerated and overwritten every time a folder replication is added,
-- removed, or toggled for this host.
settings {
  logfile = "/var/log/lsyncd/lsyncd.log",
  statusFile = "/var/log/lsyncd/lsyncd-status.log",
  statusInterval = 10,
}

${syncBlocks}
`;
}

/** Lua's own single-quoted string escaping — the config values here (paths, ssh command lines)
 * can contain characters Lua would otherwise choke on. */
function luaString(value: string): string {
  return `'${value.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
}

/** Regenerates and pushes the combined lsyncd config for every enabled 'folder' replication
 * sourced from `hostId`, then (re)starts the service — called after any change to make sure the
 * live config always matches what's configured in the panel. */
async function reconcileLsyncdOnHost(hostId: number): Promise<void> {
  const entries = listReplications().filter((r) => r.kind === "folder" && r.enabled && r.sourceHostId === hostId);

  if (entries.length === 0) {
    // Nothing left to sync from this host — stop and disable the service rather than leave it
    // running against a now-empty (or stale) config.
    await runSshCommand(hostId, `systemctl stop lsyncd 2>/dev/null; systemctl disable lsyncd 2>/dev/null; true`, {
      sudo: true,
      timeoutMs: SETUP_TIMEOUT_MS,
    });
    return;
  }

  const built = await Promise.all(
    entries.map(async (r) => {
      const keyPath = await ensurePrivateKeyDeployed(r.sourceHostId);
      const dest = getHostConnectionInfo(r.targetHostId);
      return {
        sourcePath: r.sourcePath,
        targetPath: r.targetPath,
        targetUser: dest.user,
        targetAddress: dest.address,
        targetPort: dest.port,
        keyPath,
        targetOwner: r.targetOwner,
        targetMode: r.targetMode,
      };
    })
  );

  const config = buildLsyncdConfig(built);
  const command = [
    `mkdir -p /etc/lsyncd /var/log/lsyncd`,
    `cat > ${LSYNCD_CONFIG_PATH} <<'HLP_LSYNCD_EOF'\n${config}\nHLP_LSYNCD_EOF`,
    `systemctl enable lsyncd >/dev/null 2>&1; systemctl restart lsyncd`,
  ].join(" && ");

  const { code, stderr } = await runSshCommand(hostId, command, { sudo: true, timeoutMs: SETUP_TIMEOUT_MS });
  if (code !== 0) throw new Error(stderr || "Impossible d'appliquer la configuration lsyncd sur la machine source.");
}

/** First-time setup for one folder replication: deploys the dedicated replication SSH key on both
 * ends, creates the destination directory (over that same key/identity — see ensureRemoteDir's own
 * doc comment for why it can't be created any other way), makes sure lsyncd is actually installed,
 * then regenerates and restarts the combined config on the source host. */
export async function setupFolderReplication(r: Replication): Promise<void> {
  updateReplicationStatus(r.id, "setting_up", "Déploiement de la clé SSH dédiée…");
  const keyPath = await ensurePrivateKeyDeployed(r.sourceHostId);
  await ensurePublicKeyAuthorized(r.targetHostId);

  updateReplicationStatus(r.id, "setting_up", "Vérification de rsync sur la machine cible…");
  await ensureRsyncReachable(r.sourceHostId, r.targetHostId, keyPath);
  await ensureRemoteDir(r.sourceHostId, r.targetHostId, r.targetPath, keyPath);

  updateReplicationStatus(r.id, "setting_up", "Installation de lsyncd sur la machine source…");
  const { code: lsyncdCheckCode } = await runSshCommand(r.sourceHostId, "command -v lsyncd", { timeoutMs: STATUS_TIMEOUT_MS });
  if (lsyncdCheckCode !== 0) {
    const { code, stderr } = await runSshCommand(
      r.sourceHostId,
      "apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq lsyncd",
      { sudo: true, timeoutMs: SETUP_TIMEOUT_MS }
    );
    if (code !== 0) {
      throw new Error(
        stderr ||
          "Impossible d'installer lsyncd automatiquement sur la machine source (elle n'utilise peut-être pas apt) — installe-le manuellement puis relance la configuration."
      );
    }
  }

  updateReplicationStatus(r.id, "setting_up", "Application de la configuration de réplication…");
  await reconcileLsyncdOnHost(r.sourceHostId);

  updateReplicationStatus(r.id, "in_sync", "lsyncd actif — synchronisation continue en cours.", true);
}

/** Re-applies the combined config on `hostId` — call after enabling/disabling/removing any folder
 * replication sourced from it, so the live lsyncd config never drifts from what's configured. */
export async function reconcileFolderReplicationsOnHost(hostId: number): Promise<void> {
  await reconcileLsyncdOnHost(hostId);
}

/** lsyncd runs continuously and pushes changes itself — there's nothing for this panel to trigger
 * on a timer, only status to observe: is the service actually up, and does its own status log show
 * anything alarming (a persistent rsync error would keep reappearing there). */
export async function checkFolderReplicationStatus(r: Replication): Promise<void> {
  const { stdout: activeOut } = await runSshCommand(r.sourceHostId, "systemctl is-active lsyncd 2>&1", {
    timeoutMs: STATUS_TIMEOUT_MS,
  });
  const active = activeOut.trim() === "active";
  if (!active) {
    updateReplicationStatus(r.id, "stopped", `Service lsyncd non actif sur la machine source (${activeOut.trim() || "état inconnu"}).`);
    return;
  }

  const { stdout: logTail } = await runSshCommand(
    r.sourceHostId,
    `tail -n 20 /var/log/lsyncd/lsyncd.log 2>/dev/null | grep -iE 'error|fail' | tail -n 3`,
    { timeoutMs: STATUS_TIMEOUT_MS }
  );
  const recentErrors = logTail.trim();
  if (recentErrors) {
    updateReplicationStatus(r.id, "error", recentErrors);
    return;
  }

  updateReplicationStatus(r.id, "in_sync", "lsyncd actif, aucune erreur récente dans son journal.", true);
}

/** Called before deleting a 'folder' replication, or the machine would keep pushing to a target
 * the panel no longer knows about — regenerates the source host's config without this entry. */
export async function teardownFolderReplication(sourceHostId: number): Promise<void> {
  await reconcileLsyncdOnHost(sourceHostId);
}
