import { runSshCommand, getHostConnectionInfo, shellQuote } from "../ssh";
import { ensurePrivateKeyDeployed, ensurePublicKeyAuthorized } from "../backup/keys";
import { ensureRemoteDir, ensureRsyncReachable } from "../backup/transfer";
import { listReplications, updateReplicationStatus, type Replication } from "./replication";
import { installPackageUniversal, restartService, stopService, serviceIsActive, diagnoseServiceFailure } from "../hostCompat";

const SETUP_TIMEOUT_MS = 60_000;
const STATUS_TIMEOUT_MS = 15_000;
// A reverse sync moves a whole directory tree back across the network (potentially everything
// written on the target during a failover), the same order of magnitude of work as the very first
// sync — needs the same generous budget, not the quick per-step timeout above.
const REVERSE_SYNC_TIMEOUT_MS = 30 * 60_000;
const LSYNCD_CONFIG_PATH = "/etc/lsyncd/lsyncd.conf.lua";

/**
 * lsyncd runs exactly one config file per service instance (the packaged systemd unit on
 * Debian/Ubuntu always points at LSYNCD_CONFIG_PATH) — so every enabled 'folder' replication whose
 * source is this host has to live together in one regenerated file, not one file per replication.
 * Regenerated in full and the service restarted on every add/remove/toggle rather than trying to
 * patch the file in place, which would need a real Lua-aware editor to do safely.
 */
function buildLsyncdConfig(
  entries: {
    sourcePath: string;
    targetPath: string;
    targetUser: string;
    targetAddress: string;
    targetPort: number;
    keyPath: string;
    targetOwner: string | null;
    targetMode: string | null;
    targetNeedsSudo: boolean;
  }[]
): string {
  const syncBlocks = entries
    .map((e) => {
      // Every item here becomes one entry in a Lua table of separate argv strings, so each has to
      // be its own properly-quoted Lua string literal (luaString handles that uniformly) — a bare
      // "-e" with no quotes would be invalid Lua syntax, not just a wrong argument.
      const extra = [
        luaString("-e"),
        luaString(
          `ssh -i ${e.keyPath} -p ${e.targetPort} -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10`
        ),
      ];
      // --chown/--chmod override whatever ownership/permissions rsync -a would otherwise carry
      // over numerically from the source (meaningless here — the receiving side runs this as its
      // own unprivileged, backup-dedicated SSH account, not root, and not necessarily sharing any
      // uid/gid with the source at all) — this is what actually gets files onto B owned by (and
      // permissioned for) whatever account runs the web server there.
      if (e.targetOwner) extra.push(luaString(`--chown=${e.targetOwner}`));
      if (e.targetMode) extra.push(luaString(`--chmod=${e.targetMode}`));

      // Hosting-panel-managed targets (CyberPanel, cPanel, Plesk...) isolate every site under its
      // own dedicated system account with restrictive permissions — a single shared, unprivileged
      // SSH account for replication hits "Permission denied" on every site whose directory it
      // doesn't itself own, and there's often no direct root SSH login to fall back to (root login
      // disabled being the security-hardened default on most cloud images). rsync_path runs the
      // *remote* rsync process through sudo instead of directly — the SSH authentication itself
      // stays the regular, unprivileged account; only the file operations on the target run
      // elevated. Requires a passwordless sudoers rule for rsync on that account (documented in the
      // panel's UI next to this option) — with none, sudo would block waiting on a password this
      // non-interactive SSH exec can never supply.
      const rsyncPath = e.targetNeedsSudo ? `\n    rsync_path = ${luaString("sudo rsync")},` : "";

      return `sync {
  default.rsyncssh,
  source = ${luaString(e.sourcePath)},
  host = ${luaString(`${e.targetUser}@${e.targetAddress}`)},
  targetdir = ${luaString(e.targetPath)},
  delay = 1,
  rsync = {
    archive = true,
    compress = true,${rsyncPath}
    _extra = {
      ${extra.join(",\n      ")}
    }
  }
}`;
    })
    .join("\n\n");

  return `-- Generated by Homelab Panel (high availability — folder replication). Do not edit by hand:
-- this file is fully regenerated and overwritten every time a folder replication is added,
-- removed, or toggled for this host.
settings {
  logfile = "/var/log/lsyncd/lsyncd.log",
  statusFile = "/var/log/lsyncd/lsyncd-status.log",
  statusInterval = 10,
}

${syncBlocks}
`;
}

/** Lua's own single-quoted string escaping — the config values here (paths, ssh command lines)
 * can contain characters Lua would otherwise choke on. */
function luaString(value: string): string {
  return `'${value.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
}

/** Regenerates and pushes the combined lsyncd config for every enabled 'folder' replication
 * sourced from `hostId`, then (re)starts the service — called after any change to make sure the
 * live config always matches what's configured in the panel. */
async function reconcileLsyncdOnHost(hostId: number): Promise<void> {
  const entries = listReplications().filter((r) => r.kind === "folder" && r.enabled && r.sourceHostId === hostId);

  if (entries.length === 0) {
    // Nothing left to sync from this host — stop and disable the service rather than leave it
    // running against a now-empty (or stale) config.
    await stopService(hostId, "lsyncd");
    return;
  }

  const built = await Promise.all(
    entries.map(async (r) => {
      const keyPath = await ensurePrivateKeyDeployed(r.sourceHostId);
      const dest = getHostConnectionInfo(r.targetHostId);
      return {
        sourcePath: r.sourcePath,
        targetPath: r.targetPath,
        targetUser: dest.user,
        targetAddress: dest.address,
        targetPort: dest.port,
        keyPath,
        targetOwner: r.targetOwner,
        targetMode: r.targetMode,
        targetNeedsSudo: r.targetNeedsSudo,
      };
    })
  );

  const config = buildLsyncdConfig(built);
  const writeCmd = [
    `mkdir -p /etc/lsyncd /var/log/lsyncd`,
    `cat > ${LSYNCD_CONFIG_PATH} <<'HLP_LSYNCD_EOF'\n${config}\nHLP_LSYNCD_EOF`,
  ].join(" && ");
  const { code: writeCode, stderr: writeErr } = await runSshCommand(hostId, writeCmd, {
    sudo: true,
    timeoutMs: SETUP_TIMEOUT_MS,
  });
  if (writeCode !== 0) throw new Error(writeErr || "Impossible d'écrire la configuration lsyncd sur la machine source.");

  // Tries systemd, then OpenRC, then SysV `service` — not every host managed by this panel runs
  // systemd (Alpine/OpenRC-based NAS firmwares, some minimal appliances).
  const { code, stderr } = await restartService(hostId, "lsyncd");
  if (code !== 0) {
    // A bare "failed to restart" tells you almost nothing on its own — the actual reason (a Lua
    // syntax error in the config just written, a broken package install, missing rsync on this
    // host) only shows up in the service's own status/journal, so it's fetched and appended here
    // rather than leaving the bare error to guess from.
    const diag = await diagnoseServiceFailure(hostId, "lsyncd").catch(() => "");
    throw new Error(
      `${stderr || "Impossible d'appliquer la configuration lsyncd sur la machine source."}${diag ? `\n\n${diag}` : ""}`
    );
  }
}

/** First-time setup for one folder replication: deploys the dedicated replication SSH key on both
 * ends, creates the destination directory (over that same key/identity — see ensureRemoteDir's own
 * doc comment for why it can't be created any other way), makes sure lsyncd is actually installed,
 * then regenerates and restarts the combined config on the source host. */
export async function setupFolderReplication(r: Replication): Promise<void> {
  updateReplicationStatus(r.id, "setting_up", "Déploiement de la clé SSH dédiée…");
  const keyPath = await ensurePrivateKeyDeployed(r.sourceHostId);
  await ensurePublicKeyAuthorized(r.targetHostId);

  updateReplicationStatus(r.id, "setting_up", "Vérification de rsync sur la machine cible… (installation automatique si absent)");
  await ensureRsyncReachable(r.sourceHostId, r.targetHostId, keyPath);
  await ensureRemoteDir(r.sourceHostId, r.targetHostId, r.targetPath, keyPath);

  updateReplicationStatus(
    r.id,
    "setting_up",
    "Installation de lsyncd sur la machine source… (peut prendre plusieurs minutes si apt/dpkg est occupé par une mise à jour en arrière-plan)"
  );
  const { code: lsyncdCheckCode } = await runSshCommand(r.sourceHostId, "command -v lsyncd", { timeoutMs: STATUS_TIMEOUT_MS });
  if (lsyncdCheckCode !== 0) {
    // Tries apt/dnf/yum/apk/pacman/zypper in turn rather than assuming Debian/Ubuntu — this panel
    // targets a heterogeneous fleet, not just apt-based distros. On apt specifically, also waits
    // out a concurrent dpkg lock (unattended-upgrades running in the background, most commonly)
    // instead of failing immediately on "Could not get lock" — see hostCompat.ts.
    await installPackageUniversal(r.sourceHostId, "lsyncd");
  }

  updateReplicationStatus(r.id, "setting_up", "Application de la configuration de réplication…");
  await reconcileLsyncdOnHost(r.sourceHostId);

  updateReplicationStatus(r.id, "in_sync", "lsyncd actif — synchronisation continue en cours.", true);
}

/**
 * Manual recovery action for after a failover: pulls the target's current directory tree back onto
 * the source, overwriting whatever's there — the scenario is a real outage on A during which
 * traffic (and writes) moved to B, so by the time A comes back its own copy is the *stale* one and
 * B holds the data that actually matters. Runs `rsync --delete` *from* the source host, pulling
 * from the target over the same dedicated key/identity already used for the forward direction (it
 * only needs read access on the target, which the existing authorized_keys entry already grants —
 * no new key or authorization required). Deliberately never automatic: this is a one-way overwrite
 * the user has to explicitly ask for, at a moment of their choosing.
 */
export async function reverseSyncFolderReplication(r: Replication): Promise<void> {
  updateReplicationStatus(r.id, "setting_up", "Resynchronisation depuis la machine cible (écrase la source)…");
  const keyPath = await ensurePrivateKeyDeployed(r.sourceHostId);
  const target = getHostConnectionInfo(r.targetHostId);
  const sshOpts = `-i ${keyPath} -p ${target.port} -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10`;
  const cmd =
    `rsync -az --delete -e ${shellQuote(`ssh ${sshOpts}`)} ` +
    `${shellQuote(`${target.user}@${target.address}:${r.targetPath}/`)} ${shellQuote(`${r.sourcePath}/`)}`;
  const { code, stderr } = await runSshCommand(r.sourceHostId, cmd, { timeoutMs: REVERSE_SYNC_TIMEOUT_MS });
  if (code !== 0) throw new Error(stderr || "Échec de la resynchronisation depuis la machine cible.");

  updateReplicationStatus(r.id, "setting_up", "Reprise de la réplication normale…");
  await reconcileLsyncdOnHost(r.sourceHostId);
  updateReplicationStatus(r.id, "in_sync", "Resynchronisé depuis la machine cible — réplication normale (source → cible) reprise.", true);
}

/** Re-applies the combined config on `hostId` — call after enabling/disabling/removing any folder
 * replication sourced from it, so the live lsyncd config never drifts from what's configured. */
export async function reconcileFolderReplicationsOnHost(hostId: number): Promise<void> {
  await reconcileLsyncdOnHost(hostId);
}

/** lsyncd runs continuously and pushes changes itself — there's nothing for this panel to trigger
 * on a timer, only status to observe: is the service actually up, and does its own status log show
 * anything alarming (a persistent rsync error would keep reappearing there). */
export async function checkFolderReplicationStatus(r: Replication): Promise<void> {
  const { active, raw } = await serviceIsActive(r.sourceHostId, "lsyncd");
  if (!active) {
    // Same reasoning as reconcileLsyncdOnHost's setup-time error: "non actif" alone gives no way
    // to tell a never-installed binary apart from a crashed one apart from a config error — pull
    // the service's own status/journal so the real cause is visible instead of just its symptom.
    const diag = await diagnoseServiceFailure(r.sourceHostId, "lsyncd").catch(() => "");
    updateReplicationStatus(
      r.id,
      "stopped",
      `Service lsyncd non actif sur la machine source (${raw || "état inconnu"}).${diag ? `\n${diag}` : ""}`
    );
    return;
  }

  const { stdout: logTail } = await runSshCommand(
    r.sourceHostId,
    `tail -n 20 /var/log/lsyncd/lsyncd.log 2>/dev/null | grep -iE 'error|fail' | tail -n 3`,
    { timeoutMs: STATUS_TIMEOUT_MS }
  );
  const recentErrors = logTail.trim();
  if (recentErrors) {
    updateReplicationStatus(r.id, "error", recentErrors);
    return;
  }

  updateReplicationStatus(r.id, "in_sync", "lsyncd actif, aucune erreur récente dans son journal.", true);
}

/** Called before deleting a 'folder' replication, or the machine would keep pushing to a target
 * the panel no longer knows about — regenerates the source host's config without this entry. */
export async function teardownFolderReplication(sourceHostId: number): Promise<void> {
  await reconcileLsyncdOnHost(sourceHostId);
}
