import { runSql, quoteIdentifier, type DbConnection } from "./sqlRunner";

export type ColumnSpec = {
  name: string;
  type: string;
  nullable: boolean;
  defaultValue?: string | null;
  primaryKey?: boolean;
  autoIncrement?: boolean;
};

export type ColumnInfo = {
  name: string;
  dataType: string;
  nullable: boolean;
  defaultValue: string | null;
  isPrimaryKey: boolean;
};

export async function listDatabases(conn: DbConnection): Promise<string[]> {
  const sql =
    conn.engine === "mysql" ? "SHOW DATABASES;" : "SELECT datname FROM pg_database WHERE datistemplate = false ORDER BY datname;";
  const result = await runSql(conn, sql);
  return result.rows.map((r) => r[0] as string);
}

export async function createDatabase(conn: DbConnection, name: string): Promise<void> {
  const sql =
    conn.engine === "mysql"
      ? `CREATE DATABASE ${quoteIdentifier("mysql", name)};`
      : `CREATE DATABASE ${quoteIdentifier("postgres", name)};`;
  await runSql(conn, sql);
}

export async function dropDatabase(conn: DbConnection, name: string): Promise<void> {
  const sql =
    conn.engine === "mysql"
      ? `DROP DATABASE ${quoteIdentifier("mysql", name)};`
      : `DROP DATABASE ${quoteIdentifier("postgres", name)};`;
  await runSql(conn, sql);
}

export async function listTables(conn: DbConnection, database: string): Promise<string[]> {
  const sql =
    conn.engine === "mysql"
      ? `SELECT table_name FROM information_schema.tables WHERE table_schema = ${sqlString(conn, database)} ORDER BY table_name;`
      : `SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename;`;
  const result = await runSql(conn, sql, database);
  return result.rows.map((r) => r[0] as string);
}

export async function dropTable(conn: DbConnection, database: string, table: string): Promise<void> {
  await runSql(conn, `DROP TABLE ${quoteIdentifier(conn.engine, table)};`, database);
}

export async function describeTable(conn: DbConnection, database: string, table: string): Promise<ColumnInfo[]> {
  if (conn.engine === "mysql") {
    const sql = `SELECT column_name, data_type, is_nullable, column_default, column_key
                 FROM information_schema.columns
                 WHERE table_schema = ${sqlString(conn, database)} AND table_name = ${sqlString(conn, table)}
                 ORDER BY ordinal_position;`;
    const result = await runSql(conn, sql, database);
    return result.rows.map((r) => ({
      name: r[0] as string,
      dataType: r[1] as string,
      nullable: r[2] === "YES",
      defaultValue: r[3],
      isPrimaryKey: r[4] === "PRI",
    }));
  }

  const columnsSql = `SELECT column_name, data_type, is_nullable, column_default
                       FROM information_schema.columns
                       WHERE table_schema = 'public' AND table_name = ${sqlString(conn, table)}
                       ORDER BY ordinal_position;`;
  const pkSql = `SELECT a.attname FROM pg_index i
                 JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
                 WHERE i.indrelid = ${sqlString(conn, table)}::regclass AND i.indisprimary;`;
  const [columns, pk] = await Promise.all([runSql(conn, columnsSql, database), runSql(conn, pkSql, database)]);
  const pkNames = new Set(pk.rows.map((r) => r[0] as string));
  return columns.rows.map((r) => ({
    name: r[0] as string,
    dataType: r[1] as string,
    nullable: r[2] === "YES",
    defaultValue: r[3],
    isPrimaryKey: pkNames.has(r[0] as string),
  }));
}

function sqlString(conn: DbConnection, value: string): string {
  // information_schema/system-catalog queries need the value as a SQL string literal, not a
  // shell-escaped one — reuses quoteLiteral's escaping rules per engine without going through the
  // heredoc/shell layer twice.
  const escaped = conn.engine === "mysql" ? value.replace(/\\/g, "\\\\").replace(/'/g, "\\'") : value.replace(/'/g, "''");
  return `'${escaped}'`;
}

function columnDefSql(conn: DbConnection, col: ColumnSpec): string {
  const parts = [quoteIdentifier(conn.engine, col.name), col.type];
  if (conn.engine === "mysql" && col.autoIncrement) parts.push("AUTO_INCREMENT");
  if (conn.engine === "postgres" && col.autoIncrement) parts.push("GENERATED BY DEFAULT AS IDENTITY");
  if (!col.nullable) parts.push("NOT NULL");
  if (col.defaultValue !== undefined && col.defaultValue !== null && col.defaultValue !== "") {
    parts.push(`DEFAULT ${col.defaultValue}`);
  }
  return parts.join(" ");
}

export async function createTable(conn: DbConnection, database: string, table: string, columns: ColumnSpec[]): Promise<void> {
  if (columns.length === 0) throw new Error("Au moins une colonne est requise.");
  const defs = columns.map((c) => columnDefSql(conn, c));
  const pkCols = columns.filter((c) => c.primaryKey).map((c) => quoteIdentifier(conn.engine, c.name));
  if (pkCols.length > 0) defs.push(`PRIMARY KEY (${pkCols.join(", ")})`);
  const sql = `CREATE TABLE ${quoteIdentifier(conn.engine, table)} (\n  ${defs.join(",\n  ")}\n);`;
  await runSql(conn, sql, database);
}

export async function addColumn(conn: DbConnection, database: string, table: string, col: ColumnSpec): Promise<void> {
  const sql = `ALTER TABLE ${quoteIdentifier(conn.engine, table)} ADD COLUMN ${columnDefSql(conn, col)};`;
  await runSql(conn, sql, database);
}

export async function dropColumn(conn: DbConnection, database: string, table: string, column: string): Promise<void> {
  const sql = `ALTER TABLE ${quoteIdentifier(conn.engine, table)} DROP COLUMN ${quoteIdentifier(conn.engine, column)};`;
  await runSql(conn, sql, database);
}
